### ISSUE TITLE
setup 301 redirects for commonly used links

### ISSUE THREAD

**Issue by brniamut** [magneticio/vamp.io#27]
for external sites and bookmarks pointing to commonly used links we need to create a 301 redirect in GH pages (https://help.github.com/articles/redirects-on-github-pages/)

**Comment by olafmol** [comment]
Please add these older links that are indexed in Google:


/installation/   -> /documentation/installation/overview/
/getting-started/  -> /documentation/installation/hello-world/
/using-vamp/ -> /documentation/using-vamp/artifacts/
/documentation/guides/ -> /documentation/tutorials/overview/

**Comment by gggina** [comment]
As a future reference. This is done by adding the old URL (the one you want to redirect) as an alias to the new destination page.
For example:
```
---
date: 2016-09-13T09:00:00+00:00
title: Artifacts
menu:
  main:
    parent: "Using Vamp"
    weight: 10
aliases:
    - /using-vamp/
---
```
