### ISSUE TITLE
Incorrect example in using-vamp/deployments

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp.io#7]
The first example on http://vamp.io/documentation/using-vamp/deployments/ seems incorrect.
I think the breed needs to be specified as a `reference` here, since it has no `deployable` and `ports`.

Or I would write it with a full inline breed example:

```yaml
---
name: my_cool_blueprint
endpoints:
  my_frontend.web: 8080/http

clusters:
  my_frontend:
    services:
      -
        breed:
          name: some_cool_breed:2.1
          deployable: company/some_cool_service:2.1
          ports:
             - web: 9000/http
        scale:
          cpu: 2
          memory: 2048MB
          instances: 2
```
